window.tyrano_lang = {
    word: {
        go_title: "타이틀로 돌아갈까요?",
        exit_game: "게임을 종료할까요?",
        not_saved: "저장된 데이터가 없습니다.",
        confirm: "확인",
        confirm_beforeunload: "저장하지 않은 진행 내용이 있습니다. 게임을 종료할까요?",
        tag: "タグ",
        not_exists: "は存在しません。",
        error: "エラーが発生しました。スクリプトを確認して下さい。",
        label: "ラベル",
        label_double: "は同一シナリオファイル内に重複しています。",
        error_occurred: "오류가 발생했습니다.",
        save_file_violation_1: "다른 곳에서 옮겨 온 저장 데이터입니다. 출처를 신뢰할 수 없다면 불러오지 마세요.",
        save_file_violation_2: "이 저장 데이터를 불러와 게임을 시작할까요?",
        save_file_violation_3: "게임 시작을 취소했습니다. 옮겨 온 저장 데이터를 제거한 뒤 다시 시작해 주세요.",
        double_start: "게임이 이미 실행 중입니다. 열려 있는 게임으로 돌아가 주세요.",
        reload: "새로고침",
        line: "{ line }行目",
        initialized_saved_data: "저장 데이터를 초기화했습니다.",
        initializing_saved_data: "저장 데이터를 초기화할까요?",
        saved_data_is_corrupted: "저장 데이터를 읽을 수 없습니다. 저장 데이터를 초기화할까요?",
        save_does_not_work: "현재 환경에서는 저장 기능을 사용할 수 없습니다.",
        undefined_tag: "タグ「{ name }」は存在しません。",
        undefined_label: "ラベル「{ name }」は存在しません。",
        undefined_character: "指定されたキャラクター「{ name }」は定義されていません。[chara_new]で定義してください。",
        undefined_face: "指定されたキャラクター「{ name }」の表情「{ face }」は定義されていません。[chara_face]で定義してください。",
        undefined_character_parts: "指定されたキャラクター「{ name }」の差分パーツは定義されていません。[chara_layer]で定義してください。",
        undefined_keyframe: "指定されたキーフレームアニメーション「{ keyframe }」は定義されていません。[keyframe]で定義してください。",
        undefined_3d_model: "指定された3Dモデル「{ name }」は定義されていません。",
        preload_failure_sound:
            "音声ファイル「{ src }」が見つかりません。場所はフルパスで指定されていますか？\n\n(適切な例) ./data/bgm/my_bgm.mp3",
        preload_failure_image:
            "画像ファイル「{ src }」が見つかりません。場所はフルパスで指定されていますか？\n\n(適切な例) ./data/image/my_image.png",
        preload_failure_video:
            "動画ファイル「{ src }」が見つかりません。場所はフルパスで指定されていますか？\n\n(適切な例) ./data/video/my_video.mp4",
        invalid_keyframe: "キーフレームが無効な値です。",
        invalid_keyframe_percentage:
            'キーフレームに設定されているパーセンテージ「{ percentage }」は無効な値です。"0%"、"30%"のように指定してください。',
        error_in_iscript: "[iscript] の内部でエラーが発生しました。",
        missing_endif: "[if] のあとに [elsif] [else] [endif] のいずれかが見つかりません。または、[if] 内のタグの数が多すぎます。",
        missing_endmacro: "[macro] のあとに [endmacro] が見つかりません。または、[macro] 内のタグの数が多すぎます。",
        missing_endignore: "[ignore] のあとに [endignore] が見つかりません。または、[ignore] 内の数が多すぎます。",
        missing_parameter: "タグ「{ tag }」にパラメーター「{ param }」は必須です。",
        if_and_endif_do_not_match: "[if] と [endif] の数が一致しません。",
        unsupported_extensions: "「{ ext }」はサポートしていないファイル形式です。",
        undefined_keyconfig:
            'キーコンフィグが定義されていません。KeyConfig.js が存在しないか、KeyConfig.js 内で構文エラーが発生している可能性があります。カンマ "," やブラケット "]" "}" が不足していないかどうか、確認してください。',
        compensate_missing_quart:
            '予期しない "]" を検知しました。パラメータのクォートの数が足りていない可能性があるため、自動的に修正して解釈します。\n\n修正前: { before }\n修正後: { after }',
        duplicate_label:
            "ラベル「{ name }」は同一シナリオファイル内に重複しています。ラベル名は同一シナリオファイル内で重複しないようにしてください。",
        file_not_found: "필요한 게임 파일을 찾지 못했습니다.",
        patch_not_found: "업데이트 파일을 찾지 못했습니다.",
        new_patch_found: "새 업데이트가 있습니다.\n\n버전: { version }\n{ message }\n\n업데이트할까요?",
        apply_web_patch: "업데이트를 시작합니다. 완료되면 게임이 자동으로 종료됩니다.",
        apply_patch_complete: "업데이트했습니다. 게임을 다시 시작해 주세요.",
        resume_game: "게임으로 돌아왔습니다.",
    },

    novel: {
        file_menu_button_save: "menu_button_save.gif",
        file_menu_button_load: "menu_button_load.gif",
        file_menu_button_message_close: "menu_message_close.gif",
        file_menu_button_skip: "menu_button_skip.gif",
        file_menu_button_title: "menu_button_title.gif",
        file_menu_button_close: "menu_button_close.png",
        file_menu_bg: "menu_bg.jpg",
        file_save_bg: "menu_save_bg.jpg",
        file_load_bg: "menu_load_bg.jpg",
        file_button_menu: "button_menu.png",
    },
};
